exclude: "docs|node_modules|migrations|.git"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args: ["backend"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["backend/api"]
        exclude: asgi.py

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        files: ^Edgar/
        args: []

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.29.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint@^8.24.0
          - eslint-plugin-react@6.10.3
          - "@typescript-eslint/eslint-plugin@^5.39.0"
          - "@typescript-eslint/parser@^5.39.0"
          - eslint-plugin-prettier@^4.2.1

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
